module.exports = {
  events: [
    {
      name: 'Vinyasa yoga',
      id: '1',
      labels: ['advance', 'exclusive', '50% discount'],
      description: 'Vinyasa means "to place in a special way" and, in this case, yoga postures.',
      timestamp: 1596285000000,
      timestring: '1st August - 6 PM',
      registeredUsers: [],
    },
    {
      name: 'Restorative yoga',
      id: '2',
      labels: ['beginner'],
      description: 'Restorative yoga focuses on winding down after a long day and relaxing your mind.',
      timestamp: 1596288600000,
      timestring: '1st August - 7 PM',
      registeredUsers: [],
    },
    {
      name: 'Hatha yoga yoga',
      id: '3',
      labels: ['beginner', 'just launched'],
      description: 'The Sanskrit term "hatha" is an umbrella term for all physical postures of yoga.',
      timestamp: 1596292200000,
      timestring: '1st August - 8 PM',
      registeredUsers: [],
    },
    {
      name: 'Restorative yoga',
      id: '5',
      labels: ['beginner'],
      description: 'Restorative yoga focuses on winding down after a long day and relaxing your mind.',
      timestamp: 1596375000000,
      timestring: '2nd August - 7 PM',
      registeredUsers: [],
    },
    {
      name: 'Yin yoga',
      id: '3',
      labels: ['intermediate', 'just launched'],
      description:
        'Yin yoga is a slow-paced style of yoga with seated postures that are held for longer periods of time.',
      timestamp: 1596375000000,
      timestring: '2nd August - 7 PM',
      registeredUsers: [],
    },
    {
      name: 'Yin yoga',
      id: '6',
      labels: ['advance', 'exclusive'],
      description:
        'Yin yoga is a slow-paced style of yoga with seated postures that are held for longer periods of time.',
      timestamp: 1596634200000,
      timestring: '5th August - 7 PM',
      registeredUsers: [],
    },
    {
      name: 'Anusara yoga',
      id: '7',
      labels: ['intermediate', 'exclusive'],
      description:
        'Anusara is a modern-day version of hatha yoga, most similar to vinyasa in that it focuses on alignment, but with more focus on the mind-body-heart connection.',
      timestamp: 1597458600000,
      timestring: '15th August - 8 AM',
      registeredUsers: [],
    },
  ],
};
